"""Build suyn keyboard-overlay atlases for input-overlay (OBS plugin).

Idle row: cream rounded card with the key's letter in Chalkboard SE Bold (mint green).
Pressed row: cream rounded card with a chibi sticker.
Row 3 has a wide spacebar tile with an avatar on the left and a logo on the right.

Outputs two PNG atlases (series1, series2) at output/wasd-suyn.png + wasd-suyn2.png.
The matching JSON layouts live next to them at output/wasd-suyn.json + wasd-suyn2.json
and are NOT regenerated by this script (they are hand-authored, identical for both series).
"""
from PIL import Image, ImageDraw, ImageFilter, ImageFont
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ASSETS = os.path.join(HERE, "assets")
OUTPUT = os.path.join(HERE, "output")

TILE = 192
CARD_INSET = 22
PAD = 28
RADIUS = 22
CARD_RGBA = (255, 246, 229, 235)
SHADOW_RGBA = (180, 140, 170, 90)
SHADOW_BLUR = 6

# Per-column (key_label, asset_filename_in_series_dir).
# The 12 columns map to atlas columns 0..11.
COLUMNS_SERIES1 = [
    ("W",     "haoye.png"),       # forward — charging excitement
    ("A",     "adddd.png"),       # left — yell in motion
    ("S",     "kuku.png"),        # back — retreat in tears
    ("D",     "tietie.png"),      # right — lean into
    ("Q",     "chigua.png"),      # skill 1 — casual poke
    ("E",     "lipu.png"),        # skill 2 — outrageous burst
    ("R",     "wocao.png"),       # skill 3 — surprise hit
    ("T",     "dacall.png"),      # ULTIMATE — max hype
    ("Tab",   "buguishini.png"),  # switch character
    ("Shift", "zhencai.png"),     # dodge / run
    ("Ctrl",  "laobandaqi.png"),  # crouch
    ("Z",     "kuizei.png"),      # special — sneaky/cheeky
]

# Series 2 uses the 9 表情包2 chibis on the letter slots, plus three special
# images for Tab/Shift/Ctrl. Order matches COLUMNS_SERIES1 labels.
# These series-2 specials don't ship with a baked-in white border like the
# chibi0X stickers do — synthesize one to match.
NEEDS_OUTLINE = {"wow.png", "stretch.jpg", "chibi_hips.png"}

COLUMNS_SERIES2 = [
    # chibi01=question mark, chibi02=angry, chibi03=cry, chibi04=peep,
    # chibi05=dizzy, chibi06=wow, chibi07=pat head, chibi08=shy, chibi09=love.
    # The 3 non-numbered specials (wow/stretch/chibi_hips) stay on Tab/Shift/Ctrl
    # so the 9 chibi0X fill the 9 game-action slots.
    ("W",     "chibi09.png"),     # forward — love/joyful run
    ("A",     "chibi04.png"),     # left — peep/sneak sideways
    ("S",     "chibi03.png"),     # back — cry/retreat
    ("D",     "chibi07.png"),     # right — pat-head/comforting
    ("Q",     "chibi02.png"),     # skill 1 — angry
    ("E",     "chibi05.png"),     # skill 2 — dizzy
    ("R",     "chibi06.png"),     # skill 3 — wow
    ("T",     "chibi01.png"),     # ULTIMATE — "?!" unexpected
    ("Tab",   "chibi_hips.png"),  # switch character — confident new pose
    ("Shift", "stretch.jpg"),     # dodge / run — warm-up
    ("Ctrl",  "wow.png"),         # crouch — (special slot)
    ("Z",     "chibi08.png"),     # special — shy/sneaky
]

# Bubbly font + mint-green colour scheme (matches the chibi's hair).
FONT_PATH = "/System/Library/Fonts/Supplemental/ChalkboardSE.ttc"
FONT_INDEX = 1  # 0=Light, 1=Regular, 2=Bold
TEXT_FILL  = (132, 200, 168, 255)
TEXT_MID   = (255, 255, 255, 255)
TEXT_OUTER = ( 70, 140, 110, 255)

# Spacebar spans 3 keys at pitch 167 + the last tile's 192: 167*2 + 192 = 526.
SPACE_W = 526
SPACE_H = TILE


def make_card_rect(w: int, h: int) -> Image.Image:
    lo = CARD_INSET
    rx = w - CARD_INSET
    by = h - CARD_INSET
    shadow = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    sd = ImageDraw.Draw(shadow)
    sd.rounded_rectangle((lo, lo + 4, rx, by), radius=RADIUS, fill=SHADOW_RGBA)
    shadow = shadow.filter(ImageFilter.GaussianBlur(SHADOW_BLUR))
    card = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    cd = ImageDraw.Draw(card)
    cd.rounded_rectangle((lo, lo, rx, by - 4), radius=RADIUS, fill=CARD_RGBA,
                          outline=(255, 255, 255, 220), width=2)
    out = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    out = Image.alpha_composite(out, shadow)
    out = Image.alpha_composite(out, card)
    return out


def make_card() -> Image.Image:
    return make_card_rect(TILE, TILE)


def fit_font_size(labels, max_w: int, max_h: int) -> int:
    size = max_h
    while size > 8:
        f = ImageFont.truetype(FONT_PATH, size, index=FONT_INDEX)
        if all((f.getbbox(l, stroke_width=6)[2] <= max_w
                and f.getbbox(l, stroke_width=6)[3] <= max_h) for l in labels):
            return size
        size -= 2
    return 12


def draw_label(card: Image.Image, label: str, font: ImageFont.FreeTypeFont) -> Image.Image:
    out = card.copy()
    d = ImageDraw.Draw(out)
    bbox = font.getbbox(label, stroke_width=6)
    tw = bbox[2] - bbox[0]
    th = bbox[3] - bbox[1]
    x = (TILE - tw) // 2 - bbox[0]
    y = (TILE - th) // 2 - bbox[1] - 4
    d.text((x, y), label, font=font, fill=TEXT_MID,
           stroke_width=8, stroke_fill=TEXT_OUTER)
    d.text((x, y), label, font=font, fill=TEXT_FILL,
           stroke_width=3, stroke_fill=TEXT_MID)
    return out


def _strip_white_bg(im: Image.Image, threshold: int = 240) -> Image.Image:
    """Knock out near-white pixels (used for JPG chibis on white backgrounds)."""
    px = im.load()
    w, h = im.size
    for y in range(h):
        for x in range(w):
            r, g, b, _a = px[x, y]
            if r >= threshold and g >= threshold and b >= threshold:
                px[x, y] = (r, g, b, 0)
    return im


def _add_sticker_outline(im: Image.Image, thickness: int = 6) -> Image.Image:
    """Add a white silhouette outline that follows the image's alpha shape,
    matching the baked-in border the chibi0X stickers already have.

    Trick: pre-composite the original onto a solid-white canvas so its
    anti-aliased edge pixels blend toward white (not dark) and never produce a
    gray/black halo when sat on top of the white outline. Then we just use the
    dilated alpha as the final mask.
    """
    pad = thickness + 4
    w, h = im.size
    bigW, bigH = w + 2 * pad, h + 2 * pad
    base = Image.new("RGBA", (bigW, bigH), (0, 0, 0, 0))
    base.paste(im, (pad, pad))
    alpha = base.split()[-1]
    # Dilated alpha = figure region + white halo around it.
    grown = alpha
    for _ in range(thickness):
        grown = grown.filter(ImageFilter.MaxFilter(3))
    grown = grown.filter(ImageFilter.GaussianBlur(0.6))
    # Composite original onto solid white → AA fringes resolve to white, not dark.
    white_bg = Image.new("RGBA", (bigW, bigH), (255, 255, 255, 255))
    on_white = Image.alpha_composite(white_bg, base)
    r, g, b, _ = on_white.split()
    return Image.merge("RGBA", (r, g, b, grown))


def paste_sticker(card: Image.Image, sticker_path: str, outline: bool = False) -> Image.Image:
    st = Image.open(sticker_path).convert("RGBA")
    if sticker_path.lower().endswith((".jpg", ".jpeg")):
        st = _strip_white_bg(st)
    inner = TILE - 2 * PAD
    st.thumbnail((inner, inner), Image.LANCZOS)
    if outline:
        st = _add_sticker_outline(st, thickness=6)
    out = card.copy()
    x = (TILE - st.width) // 2
    y = (TILE - st.height) // 2
    out.alpha_composite(st, (x, y))
    return out


def _circle_crop(im: Image.Image, size: int) -> Image.Image:
    w, h = im.size
    s = min(w, h)
    im = im.crop(((w - s) // 2, (h - s) // 2, (w + s) // 2, (h + s) // 2))
    im = im.resize((size, size), Image.LANCZOS)
    mask = Image.new("L", (size, size), 0)
    ImageDraw.Draw(mask).ellipse((0, 0, size, size), fill=255)
    out = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    out.paste(im, (0, 0), mask)
    return out


def _crop_sticky_bottom() -> Image.Image:
    """Crop just the icon + 劳资蜀道山 glyphs from 便利贴.jpg with the sticky-note
    background fully removed (uses a luminance threshold — the BG is light cyan,
    not pure white, so a plain white-strip doesn't work)."""
    im = Image.open(os.path.join(ASSETS, "space", "sticky-note.jpg")).convert("RGB")
    # Tight box around icon+text only — excludes the dashed border above and
    # the dashed pocket-divider below. Source image is 1555x1555.
    band = im.crop((270, 1200, 1280, 1440))
    w, h = band.size
    src = band.load()
    out = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    dst = out.load()
    hi, lo = 215, 165  # luminance thresholds for fade-to-transparent
    for y in range(h):
        for x in range(w):
            r, g, b = src[x, y]
            lum = 0.299 * r + 0.587 * g + 0.114 * b
            if lum >= hi:
                continue  # background → transparent
            if lum <= lo:
                dst[x, y] = (r, g, b, 255)
            else:
                # smooth anti-aliased edges
                alpha = int(255 * (hi - lum) / (hi - lo))
                dst[x, y] = (r, g, b, alpha)
    return out


def build_spacebar_tile(pressed: bool) -> Image.Image:
    """Idle: avatar (left, circle) + Suyn logo (right), symmetric margins.
       Pressed: bottom strip of 便利贴 (icon + 劳资蜀道山)."""
    tile = make_card_rect(SPACE_W, SPACE_H)

    if pressed:
        # Pink tint + sticky-note bottom strip, centered
        tint = Image.new("RGBA", (SPACE_W, SPACE_H), (255, 220, 235, 60))
        tile.alpha_composite(tint)
        band = _crop_sticky_bottom()
        max_w = SPACE_W - 2 * CARD_INSET - 48
        max_h = SPACE_H - 2 * CARD_INSET - 28
        band.thumbnail((max_w, max_h), Image.LANCZOS)
        bx = (SPACE_W - band.width) // 2
        by = (SPACE_H - band.height) // 2
        tile.alpha_composite(band, (bx, by))
        return tile

    # Idle: avatar + logo with symmetric margins, snug together
    avatar_sz = 110          # a bit smaller than before
    gap       = 48           # space between avatar and logo
    logo_w    = 210
    logo_src  = Image.open(os.path.join(ASSETS, "space", "suyn-logo.webp")).convert("RGBA")
    logo_h    = int(logo_src.height * logo_w / logo_src.width)
    logo      = logo_src.resize((logo_w, logo_h), Image.LANCZOS)

    content_w = avatar_sz + gap + logo_w
    margin    = (SPACE_W - content_w) // 2   # equal left/right margin

    avatar = _circle_crop(
        Image.open(os.path.join(ASSETS, "space", "avatar.jpg")).convert("RGBA"),
        avatar_sz,
    )
    tile.alpha_composite(avatar, (margin, (SPACE_H - avatar_sz) // 2))
    tile.alpha_composite(logo,   (margin + avatar_sz + gap, (SPACE_H - logo_h) // 2))
    return tile


# The plugin auto-computes the pressed sprite location as
#   pressed = (mapping.x, mapping.y + mapping.cy + CFG_INNER_BORDER, ...)
# with CFG_INNER_BORDER = 3 (see input-overlay's element_button.cpp).
# So pressed tiles must be drawn directly below idle tiles with a 3px gutter.
BORDER = 3
KEY_IDLE_Y    = 0
KEY_PRESS_Y   = KEY_IDLE_Y + TILE + BORDER          # 195
SPACE_IDLE_Y  = KEY_PRESS_Y + TILE + BORDER         # 390
SPACE_PRESS_Y = SPACE_IDLE_Y + TILE + BORDER        # 585
ATLAS_H       = SPACE_PRESS_Y + TILE                # 777


ROW1_COLS = 8   # WASDQERT on the first idle/pressed row-pair
SPACE_COL = 4   # spacebar sits at x = 4*TILE = 768 on the second row-pair
ATLAS_W   = max(ROW1_COLS * TILE, SPACE_COL * TILE + SPACE_W)  # = 1536


def build_atlas(out_path: str, series_dir: str, columns, font):
    """Atlas layout (with 3px gutters required by the plugin's auto-press logic):
       Row-pair 1  y=0..192   idle  (cols 0..7  = WASDQERT)
                    y=195..387 pressed
       Row-pair 2  y=390..582 idle  (cols 0..3 of remaining keys, then spacebar)
                    y=585..777 pressed
    """
    atlas = Image.new("RGBA", (ATLAS_W, ATLAS_H), (0, 0, 0, 0))
    for col, (label, fname) in enumerate(columns):
        if col < ROW1_COLS:
            x, idle_y, press_y = col * TILE, KEY_IDLE_Y, KEY_PRESS_Y
        else:
            x = (col - ROW1_COLS) * TILE
            idle_y, press_y = SPACE_IDLE_Y, SPACE_PRESS_Y
        idle_tile = draw_label(make_card(), label, font)
        sticker = os.path.join(ASSETS, series_dir, fname)
        pressed_card = make_card()
        tint = Image.new("RGBA", (TILE, TILE), (255, 220, 235, 60))
        pressed_card.alpha_composite(tint)
        pressed_tile = paste_sticker(pressed_card, sticker,
                                     outline=fname in NEEDS_OUTLINE)
        atlas.alpha_composite(idle_tile,    (x, idle_y))
        atlas.alpha_composite(pressed_tile, (x, press_y))

    space_x = SPACE_COL * TILE
    atlas.alpha_composite(build_spacebar_tile(pressed=False), (space_x, SPACE_IDLE_Y))
    atlas.alpha_composite(build_spacebar_tile(pressed=True),  (space_x, SPACE_PRESS_Y))

    # Watermark sits in the small unused strip to the right of the spacebar
    # (x = space_x+SPACE_W .. ATLAS_W, y = SPACE_IDLE_Y .. ATLAS_H). No `mapping`
    # rect covers this region and the plugin's auto-computed pressed rects
    # don't either, so it shows in the PNG but is invisible inside OBS.
    wm_font = ImageFont.truetype(FONT_PATH, 22, index=FONT_INDEX)
    wm_text = "made by tc-imba"
    wm_layer = Image.new("RGBA", atlas.size, (0, 0, 0, 0))
    d = ImageDraw.Draw(wm_layer)
    bbox = wm_font.getbbox(wm_text)
    tw, th = bbox[2] - bbox[0], bbox[3] - bbox[1]
    safe_x0 = space_x + SPACE_W
    wx = safe_x0 + ((ATLAS_W - safe_x0) - tw) // 2 - bbox[0]
    wy = atlas.size[1] - th - 18 - bbox[1]
    d.text((wx, wy), wm_text, font=wm_font, fill=(120, 120, 120, 220))
    atlas.alpha_composite(wm_layer)

    atlas.save(out_path, "PNG", optimize=True)
    print(f"Wrote {out_path}  {atlas.size}  {os.path.getsize(out_path):,} bytes")


def main():
    os.makedirs(OUTPUT, exist_ok=True)
    inner = TILE - 2 * CARD_INSET - 16
    size = fit_font_size([c[0] for c in COLUMNS_SERIES1], inner, inner)
    font = ImageFont.truetype(FONT_PATH, size, index=FONT_INDEX)

    build_atlas(os.path.join(OUTPUT, "wasd-suyn.png"),  "series1", COLUMNS_SERIES1, font)
    build_atlas(os.path.join(OUTPUT, "wasd-suyn2.png"), "series2", COLUMNS_SERIES2, font)


if __name__ == "__main__":
    main()
